spring:
  application:
    name: location
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/location_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
jwt:
  secret-key: ihcTmpBoN8Pww9EebY3OZowzR5HAm0ADpPIomN8nuk


